// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc1
// source: pet.proto

package pet_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 宠物信息结构
type PetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // 宠物名字
	Species       string                 `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"`                                // 宠物种类，比如狗、猫等
	Breed         string                 `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`                                    // 品种
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`                                  // 性别
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`                                //体重
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`                                    //颜色
	AvatarUrl     string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`           //图像
	IsSterilized  bool                   `protobuf:"varint,8,opt,name=is_sterilized,json=isSterilized,proto3" json:"is_sterilized,omitempty"` // 是否绝
	Phone         string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`                                    //电话
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetInfo) Reset() {
	*x = PetInfo{}
	mi := &file_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetInfo) ProtoMessage() {}

func (x *PetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetInfo.ProtoReflect.Descriptor instead.
func (*PetInfo) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

func (x *PetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetInfo) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *PetInfo) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *PetInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PetInfo) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PetInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PetInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PetInfo) GetIsSterilized() bool {
	if x != nil {
		return x.IsSterilized
	}
	return false
}

func (x *PetInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 批量创建宠物请求
type CreatePetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*PetInfo             `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetsRequest) Reset() {
	*x = CreatePetsRequest{}
	mi := &file_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetsRequest) ProtoMessage() {}

func (x *CreatePetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetsRequest.ProtoReflect.Descriptor instead.
func (*CreatePetsRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetsRequest) GetPets() []*PetInfo {
	if x != nil {
		return x.Pets
	}
	return nil
}

// 批量创建宠物响应，返回创建成功的宠物ID列表
type CreatePetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetIds        []uint64               `protobuf:"varint,1,rep,packed,name=pet_ids,json=petIds,proto3" json:"pet_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetsResponse) Reset() {
	*x = CreatePetsResponse{}
	mi := &file_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetsResponse) ProtoMessage() {}

func (x *CreatePetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetsResponse.ProtoReflect.Descriptor instead.
func (*CreatePetsResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePetsResponse) GetPetIds() []uint64 {
	if x != nil {
		return x.PetIds
	}
	return nil
}

// 查询单个宠物请求
type GetPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 宠物名字
	Species       string                 `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"` // 宠物种类，比如狗、猫等
	Breed         string                 `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{3}
}

func (x *GetPetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPetRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *GetPetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *GetPetRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 查询单个宠物响应
type GetPetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *PetInfo               `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetResponse) Reset() {
	*x = GetPetResponse{}
	mi := &file_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetResponse) ProtoMessage() {}

func (x *GetPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetResponse.ProtoReflect.Descriptor instead.
func (*GetPetResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{4}
}

func (x *GetPetResponse) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

var File_pet_proto protoreflect.FileDescriptor

const file_pet_proto_rawDesc = "" +
	"\n" +
	"\tpet.proto\x12\x03pet\"\xed\x01\n" +
	"\aPetInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x02 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x03 \x01(\tR\x05breed\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12#\n" +
	"\ris_sterilized\x18\b \x01(\bR\fisSterilized\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\"5\n" +
	"\x11CreatePetsRequest\x12 \n" +
	"\x04pets\x18\x01 \x03(\v2\f.pet.PetInfoR\x04pets\"-\n" +
	"\x12CreatePetsResponse\x12\x17\n" +
	"\apet_ids\x18\x01 \x03(\x04R\x06petIds\"i\n" +
	"\rGetPetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x02 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x03 \x01(\tR\x05breed\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"0\n" +
	"\x0eGetPetResponse\x12\x1e\n" +
	"\x03pet\x18\x01 \x01(\v2\f.pet.PetInfoR\x03pet2~\n" +
	"\n" +
	"PetService\x12=\n" +
	"\n" +
	"CreatePets\x12\x16.pet.CreatePetsRequest\x1a\x17.pet.CreatePetsResponse\x121\n" +
	"\x06GetPet\x12\x12.pet.GetPetRequest\x1a\x13.pet.GetPetResponseB\fZ\n" +
	".;pet_grpcb\x06proto3"

var (
	file_pet_proto_rawDescOnce sync.Once
	file_pet_proto_rawDescData []byte
)

func file_pet_proto_rawDescGZIP() []byte {
	file_pet_proto_rawDescOnce.Do(func() {
		file_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)))
	})
	return file_pet_proto_rawDescData
}

var file_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pet_proto_goTypes = []any{
	(*PetInfo)(nil),            // 0: pet.PetInfo
	(*CreatePetsRequest)(nil),  // 1: pet.CreatePetsRequest
	(*CreatePetsResponse)(nil), // 2: pet.CreatePetsResponse
	(*GetPetRequest)(nil),      // 3: pet.GetPetRequest
	(*GetPetResponse)(nil),     // 4: pet.GetPetResponse
}
var file_pet_proto_depIdxs = []int32{
	0, // 0: pet.CreatePetsRequest.pets:type_name -> pet.PetInfo
	0, // 1: pet.GetPetResponse.pet:type_name -> pet.PetInfo
	1, // 2: pet.PetService.CreatePets:input_type -> pet.CreatePetsRequest
	3, // 3: pet.PetService.GetPet:input_type -> pet.GetPetRequest
	2, // 4: pet.PetService.CreatePets:output_type -> pet.CreatePetsResponse
	4, // 5: pet.PetService.GetPet:output_type -> pet.GetPetResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pet_proto_init() }
func file_pet_proto_init() {
	if File_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pet_proto_goTypes,
		DependencyIndexes: file_pet_proto_depIdxs,
		MessageInfos:      file_pet_proto_msgTypes,
	}.Build()
	File_pet_proto = out.File
	file_pet_proto_goTypes = nil
	file_pet_proto_depIdxs = nil
}
